3813 pkg build needs to fail when sub-builds fail 6293 ksh93-isms in depot start method 6294 mako, pyopenssl, cherrypy package makefiles try to be too clever 6295 pkg(5) doesn't build on /usr/sfw openssl nevada systems 6304 Add syntax check earlier in the build, and fail when it fails 6316 pkgdefs build needs makeover

diff --git a/src/pkgdefs/SUNWipkg-brand/Makefile b/src/pkgdefs/SUNWipkg-brand/Makefile
--- a/src/pkgdefs/SUNWipkg-brand/Makefile
+++ b/src/pkgdefs/SUNWipkg-brand/Makefile
@@ -66,6 +66,14 @@ prototype: FRC
 		$$3 ~ /^etc(\/zones(\/.*)?)?$$/ { \
 			print \
 		}' > prototype
+	if [ `wc -l prototype | awk '{print $$1}'` -eq 0 ]; then \
+		echo "ERROR: prototype file came up empty!"; \
+		exit 1; \
+	fi
+
+clobber:
+	rm -f prototype
+	rm -rf $(PKGARCHIVE)/$(PKG)
 
 $(PKGARCHIVE):
 	[ -d $(PKGARCHIVE) ] || mkdir -p $(PKGARCHIVE)
diff --git a/src/pkgdefs/SUNWipkg-gui-data/Makefile b/src/pkgdefs/SUNWipkg-gui-data/Makefile
--- a/src/pkgdefs/SUNWipkg-gui-data/Makefile
+++ b/src/pkgdefs/SUNWipkg-gui-data/Makefile
@@ -60,6 +60,14 @@ prototype: FRC
 		$$3 ~ /^usr\/share\/package-manager\/data/ { \
 			print \
 		}' > prototype
+	if [ `wc -l prototype | awk '{print $$1}'` -eq 0 ]; then \
+		echo "ERROR: prototype file came up empty!"; \
+		exit 1; \
+	fi
+
+clobber:
+	rm -f prototype
+	rm -rf $(PKGARCHIVE)/$(PKG)
 
 $(PKGARCHIVE):
 	[ -d $(PKGARCHIVE) ] || mkdir -p $(PKGARCHIVE)
diff --git a/src/pkgdefs/SUNWipkg-um/Makefile b/src/pkgdefs/SUNWipkg-um/Makefile
--- a/src/pkgdefs/SUNWipkg-um/Makefile
+++ b/src/pkgdefs/SUNWipkg-um/Makefile
@@ -66,10 +66,18 @@ prototype: FRC
 		$$3 ~ /^(usr(\/lib(\/updatemanagernotifier)?)?|usr\/lib\/update-manager(\/update-refresh.sh)?|usr(\/bin(\/updatemanager)?)?|var(\/svc(\/manifest(\/application\/(pkg-update.xml)?)?)?)?|etc(\/xdg(\/autostart(\/updatemanagernotifier.desktop)?)?)?|etc\/gconf(\/schemas(\/updatemanager-preferences.schemas)?)?|lib(\/svc(\/method(\/pkg-update)?)?)?|usr(\/share(\/update-manager(\/updatemanager.glade|\/PM_app_48x.png|\/PM_package_36x.png)?|\/applications(\/updatemanager.desktop)?|\/icons(\/hicolor(\/48x48(\/apps(\/updatemanager.png)?)?)?)?|\/icons(\/update-manager(\/notify_update.png|\/status_checkmark.png|\/status_blank.png)?)?)?)?)$$/ { \
 			print \
 		}' > prototype
+	if [ `wc -l prototype | awk '{print $$1}'` -eq 0 ]; then \
+		echo "ERROR: prototype file came up empty!"; \
+		exit 1; \
+	fi
 
 # This will only work if there's a server running, so allow failure.
 img-pkg: sysv-pkg
 	-../../util/distro-import/solaris.py -b 0.0 -w $(PKGARCHIVE) SUNWipkg.import
+
+clobber:
+	rm -f prototype
+	rm -rf $(PKGARCHIVE)/$(PKG)
 
 $(PKGARCHIVE):
 	[ -d $(PKGARCHIVE) ] || mkdir -p $(PKGARCHIVE)
diff --git a/src/pkgdefs/SUNWipkg/Makefile b/src/pkgdefs/SUNWipkg/Makefile
--- a/src/pkgdefs/SUNWipkg/Makefile
+++ b/src/pkgdefs/SUNWipkg/Makefile
@@ -60,6 +60,14 @@ prototype: FRC
 		$$3 !~ /^etc|lib\/svc\/method\/pkg-update|var\/svc\/manifest\/application\/pkg-update.xml|usr\/lib\/brand|usr\/lib(\/update-manager|\/updatemanagernotifier)|usr(\/lib\/python2.4\/vendor-packages(\/[Mm]ako|\/cherrypy|\/OpenSSL|\/pkg\/gui)|\/bin(\/packagemanager|\/updatemanager|\/mako-render)|\/share(\/package-manager|\/update-manager|\/locale|\/applications|\/icons|\/gnome))/ { \
 			print \
 		}' > prototype
+	if [ `wc -l prototype | awk '{print $$1}'` -eq 0 ]; then \
+		echo "ERROR: prototype file came up empty!"; \
+		exit 1; \
+	fi
+
+clobber:
+	rm -f prototype
+	rm -rf $(PKGARCHIVE)/$(PKG)
 
 $(PKGARCHIVE):
 	[ -d $(PKGARCHIVE) ] || mkdir -p $(PKGARCHIVE)
diff --git a/src/pkgdefs/SUNWpython-mako/Makefile b/src/pkgdefs/SUNWpython-mako/Makefile
--- a/src/pkgdefs/SUNWpython-mako/Makefile
+++ b/src/pkgdefs/SUNWpython-mako/Makefile
@@ -18,7 +18,7 @@
 #
 # CDDL HEADER END
 #
-# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 
@@ -34,7 +34,7 @@ PROTOLOC = $(ROOT)/usr/lib/python2.4/vendor-packages/mako
 install: sysv-pkg
 
 sysv-pkg: $(PKGARCHIVE) prototype
-	[ -f $(PKGARCHIVE)/$(PKG)/pkgmap ] || pkgmk -a $(MACH) -o -r $(ROOT) -d $(PKGARCHIVE)
+	pkgmk -a $(MACH) -o -r $(ROOT) -d $(PKGARCHIVE)
 
 prototype: $(PROTOLOC)
 	(cd $(ROOT); pkgproto .) | \
@@ -65,6 +65,10 @@ prototype: $(PROTOLOC)
 				print \
 			} \
 		}' > prototype
+	if [ `wc -l prototype | awk '{print $$1}'` -eq 0 ]; then \
+		echo "ERROR: prototype file came up empty!"; \
+		exit 1; \
+	fi
 
 clobber:
 	rm -f prototype
