15807357 need an Apache-based pkg.depotd

diff --git a/src/svc/svc-pkg-depot b/src/svc/svc-pkg-depot
--- a/src/svc/svc-pkg-depot
+++ b/src/svc/svc-pkg-depot
@@ -19,129 +19,243 @@
 #
 # CDDL HEADER END
 #
-# Copyright (c) 2009, 2010 Oracle and/or its affiliates.  All rights reserved.
+#
+# Copyright (c) 2013, Oracle and/or its affiliates. All rights reserved.
 #
 
-# Load SMF constants and functions
 . /lib/svc/share/smf_include.sh
 
-if [[ -z "$SMF_FMRI" ]]; then
-	echo "this script can only be invoked by smf(5)"
-	exit $SMF_EXIT_ERR_NOSMF
-fi
+APACHE_HOME=/usr/apache2/2.2
+APACHE_ETC_ROOT=/etc/pkg/depot
+APACHE_BIN=${APACHE_HOME}/bin/64
 
-case "$1" in
-'start')
-	# Handles depot startup
+#
+# Calling $APACHE_BIN/apachectl would source $APACHE_BIN/envvars, which
+# in turn would source /etc/apache2/2.2/envvars, if it exists.
+#
+# We want to keep the depot service completely separate from
+# the site system configuration used by svc:/network/http:apache22
+# avoiding /etc/apache2, which means we must avoid apachectl.
+#
+# In this method script, we call httpd directly instead, but as a
+# result, we also need to include the relevant contents of
+# $APACHE_BIN/envvars - setting $LD_LIBRARY_PATH as it does.
+#
+HTTPD=${APACHE_BIN}/httpd.worker
+LD_LIBRARY_PATH=${APACHE_HOME}/lib/64:${LD_LIBRARY_PATH}
+export LD_LIBRARY_PATH
 
-	# retrieve the pkg_root property. If the variable is left empty
-	# pkg_root is /
-	pkg_root=$(svcprop -p pkg/pkg_root $SMF_FMRI)
-	if [[ $? -ne 0 ]]; then
-		echo "service property pkg/pkg_root not defined for" \
-		    "service: $SMF_FMRI"
-		exit $SMF_EXIT_ERR_CONFIG
-	fi
 
-	# make sure pkg_root ends with a /
-	echo $pkg_root | grep /$ >/dev/null
-	if [[ $? -ne 0 ]]; then
-		pkg_root="${pkg_root}/"
-	fi
-
-	# adjust the PYTHONPATH to point to the current environment
-	# we need to make sure to adjust the PYTHONPATH accordingly
-	# to a Python 2.4 or 2.6 environment
-	python_ver=$(head -1 ${pkg_root}usr/lib/pkg.depotd 2>/dev/null |
-	    awk -F/ '{print $NF}')
-	if [[ $python_ver != *python* ]]; then
-		echo "invalid python version $python_ver found in"
-		echo "${pkg_root}usr/lib/pkg.depotd"
+function check_prop {
+	if [ -z "$1" ]; then
+		echo "ERROR: SMF property for $2 was empty"
 		exit $SMF_EXIT_ERR_FATAL
 	fi
+}
 
-	PYTHONPATH=${pkg_root}usr/lib/${python_ver}/vendor-packages/:$PYTHONPATH
+function get_pair {
+        NAME=$1
+        shift 2
+        echo "${NAME}=\"$@\""
+        echo "export ${NAME}"
+}
 
-	export PYTHONPATH
+# A function to pull in the config properties from the FMRI given
+# as the first argument. This allows us to make a single call
+# to svcprop, rather than calling svcprop for each value we
+# want to retrieve.
+function get_smf_props {
 
-	#
-	# If this process has net_privaddr, then we pass it along.
-	# If not, we ensure that we don't specify it, since that will
-	# cause ppriv to throw an error.
-	#
-	privaddr=""
-	ppriv -v $$ | grep 'E: ' | grep net_privaddr > /dev/null 2>&1
-	if [[ $? == 0 ]]; then
-		echo "Dropping net_privaddr privilege."
-		privaddr=",net_privaddr"
-	fi
+	IFS="
+"
+	SMF_PROPS="$(svcprop -t -p config $1 |\
+        	sed -e 's#config/#depot_#g' -e 's/$/,/g')"
+	IFS=,
+	for line in $SMF_PROPS ; do
+        	IFS=' 
+'
+        	eval $(get_pair $line)
+	done
+}
 
-	#
-	# Build up the privileges available starting with "basic".  This
-	# provides some protection even when the depot runs as root.
-	#
-	wrapper="ppriv -s \
-            A=basic,-file_link_any,-proc_info,-proc_session$privaddr -e"
 
-	# Build the command to start pkg.depotd.
-	cmd="$wrapper ${pkg_root}usr/lib/pkg.depotd --cfg $SMF_FMRI"
-
-	# Echo the command so that the log contains the command used to start
-	# the depot.
-	echo $cmd
-
-	exec $cmd
-
-	;;
-
-'stop')
-	#
-	# Strategy: First, try shutting down depot using polite kill.  Use up
-	# as much as possible of the allotted timeout period waiting for polite
-	# kill to take effect.  As time runs out, try a more aggressive kill.
-	#
-	SVC_TIMEOUT=`svcprop -p stop/timeout_seconds $SMF_FMRI`
-	if [[ $? -ne 0 ]]; then
-		echo "service property stop/timeout_seconds not defined" \
-		    "for service: $SMF_FMRI"
-		exit $SMF_EXIT_ERR_CONFIG
-	fi
-
-	#
-	# Note that we're working around an oddity in smf_kill_contract: it
-	# waits in 5 second chunks and can overshoot the specified timeout
-	# by as many as 4 seconds.  Example: a specified wait of 6 will result
-	# in a wait of 10 seconds in reality.  Since we may potentially do a
-	# first kill and then a second, we must ensure that at least 8 seconds
-	# of slop is left in reserve.  To be paranoid, we go for 10.
-	#
-	((POLITE=$SVC_TIMEOUT - 10))
-	if [[ $POLITE -gt 0 ]]; then
-		smf_kill_contract $2 TERM 1 $POLITE
-		ret=$?
-		# '2' indicates timeout with non-empty contract.
-		if [[ $ret -eq 2 ]]; then
-			echo "Gentle contract kill timed out after" \
-			    "$POLITE seconds, trying SIGKILL." >&2
-			#
-			# Again, despite the specified timeout, this will
-			# take a minimum of 5 seconds to complete.
-			#
-			smf_kill_contract $2 KILL 1 1
-			if [[ $ret -ne 0 ]]; then
-				exit $SMF_EXIT_ERR_FATAL
-			fi
+function check_failure {
+	RESULT=$1
+	MESSAGE=$2
+	NON_FATAL=$3
+	if [ $RESULT -ne 0 ]; then
+		echo $MESSAGE
+		if [ -n "$NON_FATAL" ]; then
+			return
 		fi
-	else
-		# If the timeout is too short, we just try once, politely.
-		smf_kill_contract $2 TERM
+		exit $SMF_EXIT_ERR_FATAL
 	fi
-	;;
+}
 
+function check_apache_failure {
+	RESULT=$1
+	MESSAGE=$2
+	if [ $RESULT -ne 0 ]; then
+		echo $MESSAGE
+		kill_apache
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+}
+
+function abspath {
+	# print a normalized version of a path, needed because
+	# many utilities will not dereference non-existent directories
+	# in path names, e.g. cat /etc/no-such-dir/../motd will fail.
+	echo $1 | /usr/bin/python -c \
+    'import os.path ; import sys ; print os.path.normpath(sys.stdin.read())'
+}
+
+function run_depot {
+
+        /usr/lib/pkg.depot-config \
+               -S \
+               -c ${depot_cache_dir} \
+               -h ${depot_host} \
+               -l ${depot_log_dir} \
+               -p ${depot_port} \
+               -r ${depot_runtime_dir} \
+               -s ${depot_cache_max} \
+               -T ${depot_template_dir} \
+               -t apache2 \
+               ${depot_allow_refresh}
+	failure=$?
+	if [ $? -ne 0 ] ; then
+		# make sure we leave nothing behind
+		kill_apache
+		kill_htcacheclean
+	        check_failure $failure \
+	            "pkg.depot-config: failed to create Apache config"
+	fi
+}
+
+function run_htcacheclean {
+	# if we dropped to maintenance and are in the process of
+	# clearing that state,  we may have htcacheclean processes
+	# hanging around.
+	kill_htcacheclean
+	if [ "${depot_cache_max}" != "0" ] ; then
+		# Start a cache cleaning daemon, scanning every 2 weeks,
+		# being intelligent about only running if the cache has
+		# changed, limiting the cache to ${depot_cache_max}
+		# megabytes, being nice about scheduling and removing
+		# empty directories if necessary.
+	       interval=$((60 * 24 * 14))
+               /usr/bin/su pkg5srv \
+		       -c "/usr/apache2/2.2/bin/htcacheclean \
+                       -d${interval} -i -l ${depot_cache_max}M -n \
+                       -p ${depot_cache_dir} \
+                       -P ${depot_cache_dir}/../depot_htcacheclean.pid \
+                       -t"
+               check_failure $? "htcacheclean failed to run cleanly"
+       fi
+}
+
+function kill_htcacheclean {
+	pid_file=$(abspath ${depot_cache_dir}/../depot_htcacheclean.pid)
+	if [ -f $pid_file ]; then
+                PID=$(< $pid_file)
+                /usr/bin/kill -TERM $PID
+                check_failure $? "failed to kill htcacheclean process\
+ $PID" "not_fatal"
+        fi
+}
+
+function kill_apache {
+	# We go to lengths to kill remaining httpd processes: if we kill
+	# just the pid, then child httpd.worker processes become
+	# zombies, hanging onto the server port, which causes problems
+	# when trying to start a service that is transitioning from
+	# maintenance.
+	# This function should only be called when the service is
+	# transitioning to maintenance: normal Apache shutdown is
+	# preferable.
+	pid_file=$(abspath ${depot_runtime_dir}/../depot_httpd.pid)
+	if [ -f $pid_file ]; then
+		PID=$(< $pid_file)
+		/usr/bin/ptree $PID | /usr/bin/awk '{print $1}' | \
+		    /usr/bin/xargs /usr/bin/kill -TERM
+		check_failure $? "failed to kill apache process $PID" \
+		    "not_fatal"
+		/usr/bin/rm $pid_file
+	fi
+}
+
+function server_ping {
+	# Ping the service, ensuring the index gets built if does
+	# not exist.
+	# Since curl --retry uses an exponential backoff algorithm, this
+	# can result in us waiting 40 seconds, which ought to be long
+	# enough for Apache to come online. (index refreshes are run in
+	# the background on the server after it has returned a response)
+	url="http://${depot_host}:${depot_port}"
+	ipv6=$(echo ${depot_host} | /usr/bin/grep :)
+	if [ -n "$ipv6" ] ; then
+		url="http://\[${depot_host}\]:${depot_port}"
+	fi
+	/usr/bin/curl -s --max-time 5 --retry 4 -o /dev/null ${url} \
+2> /dev/null
+	check_failure $? "Unable to access the server at ${url}. Check\
+ the SMF service log or the error log at ${depot_log_dir}/error_log for\
+ more information, if any."
+}
+
+get_smf_props $SMF_FMRI
+check_prop ${depot_host} config/host
+check_prop ${depot_port} config/port
+check_prop ${depot_log_dir} config/log_dir
+check_prop ${deport_template_dir} config/template_dir
+check_prop ${depot_runtime_dir} config/runtime_dir
+check_prop ${depot_cache_dir} config/cache_dir
+check_prop ${depot_cache_max} config/cache_max
+check_prop ${depot_allow_refresh} config/allow_refresh
+if [ "${depot_allow_refresh}" == "true" ] ; then
+	depot_allow_refresh="-A"
+else
+	depot_allow_refresh=""
+fi
+
+FAILED_TO_RUN="Server failed to %s. Check the SMF service log or the\
+ error log at ${depot_log_dir}/error_log for more information, if any."
+
+case "$1" in
+"start")
+	cmd="start"
+	run_depot
+	run_htcacheclean
+        emsg=$(/usr/bin/printf ${FAILED_TO_RUN} start)
+	${HTTPD} -f ${depot_runtime_dir}/depot_httpd.conf \
+            ${STARTUP_OPTIONS} -k ${cmd} 2>&1
+ 	check_apache_failure $? $emsg
+        server_ping
+	;;
+"refresh")
+	cmd="graceful"
+	run_depot
+	kill_htcacheclean
+	run_htcacheclean
+        emsg=$(/usr/bin/printf ${FAILED_TO_RUN} refresh)
+	${HTTPD} -f ${depot_runtime_dir}/depot_httpd.conf \
+            ${STARTUP_OPTIONS} -k ${cmd} 2>&1
+	check_apache_failure $? $emsg
+        server_ping
+	;;
+"stop")
+	cmd="stop"
+	kill_htcacheclean
+        emsg=$(/usr/bin/printf ${FAILED_TO_RUN} stop)
+	${HTTPD} -f ${depot_runtime_dir}/depot_httpd.conf \
+            ${STARTUP_OPTIONS} -k ${cmd} 2>&1
+	check_apache_failure $? $emsg
+	;;
 *)
-	echo "Usage: $0 { start | stop }"
+	echo "Usage: $0 {start|stop|refresh}"
 	exit $SMF_EXIT_ERR_CONFIG
 	;;
-
 esac
+
 exit $SMF_EXIT_OK
