18888 manifests should be renamed

diff --git a/src/pkg/Makefile b/src/pkg/Makefile
--- a/src/pkg/Makefile
+++ b/src/pkg/Makefile
@@ -23,11 +23,14 @@
 
 PKGVERS_COMPONENT = 0.5.11
 PKGVERS_BUILTON   = 5.11
-BUILDNUM.cmd      = hg tags | nawk '$$1 ~ /^in[0-9]*$$/ {print substr($$1, 3) + 1; exit}'
+BUILDNUM.cmd      = \
+	hg tags | nawk '$$1 ~ /^in[0-9]*$$/ {print substr($$1, 3) + 1; exit}'
 BUILDNUM          = $(BUILDNUM.cmd:sh)
 CHANGESET.cmd     = hg id -i
 CHANGESET         = $(CHANGESET.cmd:sh)
-CURBUILD.cmd      = $(PKG) -R / list -H osnet-incorporation | sed -e 's/.*-0\.\([^ .]*\).*/\1/'
+CURBUILD.cmd      = \
+	$(PKG) -R / list -H osnet-incorporation | \
+		sed -e 's/.*-0\.\([^ .]*\).*/\1/'
 CURBUILD          = $(CURBUILD.cmd:sh)
 PKGVERS_BRANCH    = 0.$(BUILDNUM)
 PKGVERS           = $(PKGVERS_COMPONENT),$(PKGVERS_BUILTON)-$(PKGVERS_BRANCH)
@@ -51,12 +54,13 @@ MANIFESTS.cmd     = \
 	m=$$($(PKGMOGRIFY) -O /dev/null *.p5m ../transforms/nopublish); \
 	echo "$$m" | while read name build; do \
 		[[ $$build -ge $${buildnum%%.*} ]] && echo $$name; \
-	done ; exit 0
+	done | sed -e 's/:/\\:/g' ; exit 0
 MANIFESTS         = $(MANIFESTS.cmd:sh)
-$(PUBLISHALL)MANIFESTS:sh      = (cd manifests; print *.p5m)
-PKGS.cmd          = print $(MANIFESTS:%.p5m=%) | sed -e s/%2F/\\//g
-PKGS              = $(PKGS.cmd:sh)
-PKGCMDENV         = PATH=$(PKGROOT)/usr/bin:/usr/sbin:/usr/bin PYTHONPATH=$(PKGROOT)/usr/lib/python2.6/vendor-packages
+$(PUBLISHALL)MANIFESTS:sh      = \
+	(cd manifests; print *.p5m | sed -e 's/:/\\:/g')
+PKGCMDENV         = \
+	PATH=$(PKGROOT)/usr/bin:/usr/sbin:/usr/bin \
+		PYTHONPATH=$(PKGROOT)/usr/lib/python2.6/vendor-packages
 PKG               = $(PKGCMDENV) pkg
 PKGDEPEND         = $(PKGCMDENV) pkgdepend
 PKGLINT           = $(PKGCMDENV) pkglint
@@ -66,7 +70,7 @@ PKGSEND           = $(PKGCMDENV) pkgsend
 MOGRIFESTS        = $(MANIFESTS:%.p5m=$(PDIR)/%.mog)
 PUBLIFESTS        = $(MANIFESTS:%.p5m=$(PDIR)/%.pub)
 DEPENDED          = $(MANIFESTS:%.p5m=$(PDIR)/%.dep)
-INCORP            = consolidation%2Fips%2Fips-incorporation
+INCORP            = consolidation\:ips\:ips-incorporation
 
 PM_TRANSFORMS     = defaults
 
@@ -134,10 +138,12 @@ $(PDIR)/$(INCORP).mog: manifests/$(INCORP).p5m $(PDIR) \
 	$(MOGRIFESTS:$(PDIR)/$(INCORP).mog=)
 	$(PKGMOGRIFY) -I transforms defaults incorp2 manifests/$(INCORP).p5m | \
 		$(PKGMOGRIFY) $(PKGMOG_DEFINES) -D DEPTYPE=incorporate \
-		-I transforms -O $@ /dev/stdin incorp $(MOGRIFESTS:$(PDIR)/$(INCORP).mog=)
+		-I transforms -O $@ /dev/stdin incorp \
+		$(MOGRIFESTS:$(PDIR)/$(INCORP).mog=)
 
 # The main mogrification rule
-$(PDIR)/%.mog: manifests/%.p5m $(PM_TRANSFORMS:%=transforms/%) $(PDIR) $(PM_TRANSFORMS:%=transforms/%)
+$(PDIR)/%.mog: manifests/%.p5m $(PM_TRANSFORMS:%=transforms/%) $(PDIR) \
+	$(PM_TRANSFORMS:%=transforms/%)
 	$(PKGMOGRIFY) $(PKGMOG_DEFINES) -I transforms -O $@ $< $(PM_TRANSFORMS)
 
 # The main dependency generation rule
@@ -152,8 +158,9 @@ $(PDIR)/.resolved: $(DEPENDED)
 
 # The main publication rule
 $(PDIR)/%.pub: $(PDIR)/.resolved $(PKGDEST)/repo
-	$(PKGSEND) -s file://$(PKGDEST)/repo publish -d $(PKGROOT) -d license_files \
-		-T \*.py --fmri-in-manifest --no-index --no-catalog $(@:%.pub=%.dep.res)
+	$(PKGSEND) -s file://$(PKGDEST)/repo publish -d $(PKGROOT) \
+		-d license_files -T \*.py --fmri-in-manifest --no-index \
+		--no-catalog $(@:%.pub=%.dep.res)
 	touch $@
 
 # Compare the proto area with the package manifests; if they've got different
@@ -180,7 +187,7 @@ check: $(PDIR)/protomanifest $(PDIR)/pkgmanifest
 # the lint run, please edit external_deps.pkglintrc
 lint: repository-metadata
 	@sed -e "s#/usr/share/lib/pkg/opensolaris.org.sections#$(PKGROOT)&#" \
-		 < ips-pkglintrc > $(PDIR)/pkglintrc
+		< ips-pkglintrc > $(PDIR)/pkglintrc
 
 	@# Ensure that the shipped pkglint_whitelist.txt is self-consistent.
 	@# That is, when sorting it in the C locale and diffing the output
@@ -191,10 +198,11 @@ lint: repository-metadata
 	@rm -rf $(PDIR)/pkglint-cache
 	@rm -f $(PDIR)/pkglint-out*
 	@if [ -n "$(PKGLINT_REF_REPO)" ]; then				\
-		env LC_ALL=C $(PKGLINT) -f $(PDIR)/pkglintrc -c $(PDIR)/pkglint-cache\
+		env LC_ALL=C $(PKGLINT) -f $(PDIR)/pkglintrc \
+			-c $(PDIR)/pkglint-cache \
 			-r $(PKGLINT_REF_REPO) -l file://$(PKGDEST)/repo; \
 	fi
-	-@if [ -z "$(PKGLINT_REF_REPO)" ]; then 			\
+	-@if [ -z "$(PKGLINT_REF_REPO)" ]; then				\
 		cat external_deps.pkglintrc >> $(PDIR)/pkglintrc;	\
 		( $(PKGLINT) -c $(PDIR)/pkglint-cache			\
 			-f $(PDIR)/pkglintrc				\
@@ -204,27 +212,27 @@ lint: repository-metadata
 			diff pkglint_whitelist.txt -			\
 			| grep -v pkglint.manifest007			\
 			| grep -v pkglint.action008			\
-			> $(PDIR)/pkglint-out-diff.txt; 		\
+			> $(PDIR)/pkglint-out-diff.txt;			\
 									\
-		egrep "^< WARNING |^< ERROR |^< CRITICAL " 		\
-			$(PDIR)/pkglint-out-diff.txt 			\
-			> $(PDIR)/pkglint-out-fixes.txt; 		\
+		egrep "^< WARNING |^< ERROR |^< CRITICAL "		\
+			$(PDIR)/pkglint-out-diff.txt			\
+			> $(PDIR)/pkglint-out-fixes.txt;		\
 		egrep -v "^< WARNING |^< ERROR |^< CRITICAL "		\
-			$(PDIR)/pkglint-out-diff.txt 			\
-			| sed -e '/^[0-9,]*[ad][0-9,]*$$/d' 		\
-			> $(PDIR)/pkglint-out-breakage.txt; 		\
+			$(PDIR)/pkglint-out-diff.txt			\
+			| sed -e '/^[0-9,]*[ad][0-9,]*$$/d'		\
+			> $(PDIR)/pkglint-out-breakage.txt;		\
 	fi
-	@if [ -s $(PDIR)/pkglint-out-fixes.txt ]; then 			\
+	@if [ -s $(PDIR)/pkglint-out-fixes.txt ]; then			\
 		echo "";						\
-		echo "The following pkglint errors are now fixed:"; 	\
-		cat $(PDIR)/pkglint-out-fixes.txt; 			\
+		echo "The following pkglint errors are now fixed:";	\
+		cat $(PDIR)/pkglint-out-fixes.txt;			\
 		echo "pkglint-whitelist.txt should be updated";		\
 	fi
-	@if [ -s $(PDIR)/pkglint-out-breakage.txt ]; then 		\
+	@if [ -s $(PDIR)/pkglint-out-breakage.txt ]; then		\
 		echo "";						\
 		echo "New pkglint errors detected:";			\
-		cat $(PDIR)/pkglint-out-breakage.txt; 			\
-		exit 1; 						\
+		cat $(PDIR)/pkglint-out-breakage.txt;			\
+		exit 1;						\
 	fi
 
 # A little bit of Python is the easiest way to generate the commandline options
@@ -241,6 +249,7 @@ $(PDIR)/protomanifest: FRC transforms/compare-strip $(PDIR)
 
 # Create a pseudo-manifest of the combined packages
 $(PDIR)/pkgmanifest: $(MOGRIFESTS) transforms/compare-strip $(PDIR)
-	$(PKGMOGRIFY) $(PKGMOG_DEFINES) transforms/compare-strip $(MOGRIFESTS) > $@
+	$(PKGMOGRIFY) $(PKGMOG_DEFINES) transforms/compare-strip $(MOGRIFESTS) \
+		> $@
 
 FRC:
