17791 ipkg brand needs to be in sync with revised dataset layout 17654 check for zonepath in GZ ROOT assumes root pool named rpool

diff --git a/src/brand/attach b/src/brand/attach
--- a/src/brand/attach
+++ b/src/brand/attach
@@ -55,6 +55,9 @@ f_nosuch_key=$(gettext "Failed to find key %s for global zone publisher")
 f_nosuch_cert=$(gettext "Failed to find cert %s for global zone publisher")
 f_ds_config=$(gettext  "Failed to configure dataset %s: could not set %s.")
 f_no_active_ds_mounted=$(gettext  "Failed to locate any dataset mounted at %s.  Attach requires a mounted dataset.")
+e_dataset_disappeared=$(gettext "Dataset %s was unexpectedly unmounted")
+e_dataset_not_mounted=$(gettext "Dataset %s exists in boot environment but not mounted")
+e_dataset_not_in_be=$(gettext "Dataset %s mountpoint %s is not under zone root %s")
 
 # Clean up on interrupt
 trap_cleanup() {
@@ -82,15 +85,20 @@ trap_exit() {
 			# Restore the zone properties for the pre-existing
 			# dataset.
 			if [[ -n "$ACTIVE_DS" ]]; then
+				zfs set canmount=off $ACTIVE_DS
+				(( $? != 0 )) && error "$f_ds_config" \
+				    "$ACTIVE_DS" "canmount=on"
 				zfs set zoned=off $ACTIVE_DS
 				(( $? != 0 )) && error "$f_ds_config" \
 				    "$ACTIVE_DS" "zoned=off"
-				zfs set canmount=on $ACTIVE_DS
-				(( $? != 0 )) && error "$f_ds_config" \
-				    "$ACTIVE_DS" "canmount=on"
 				zfs set mountpoint=$ZONEROOT $ACTIVE_DS
 				(( $? != 0 )) && error "$f_ds_config" \
 				    "$ACTIVE_DS" "mountpoint=$ZONEROOT"
+				zfs set canmount=on $ACTIVE_DS
+				(( $? != 0 )) && error "$f_ds_config" \
+				    "$ACTIVE_DS" "canmount=on"
+				zfs mount "$ACTIVE_DS" || \
+				    error "$e_mount1_failed" "$ACTIVE_DS"
 			fi
 		fi
 		log "$m_failed"
@@ -105,23 +113,19 @@ install_media="-"
 trap trap_cleanup INT
 trap trap_exit EXIT
 
-#set -o xtrace
-
 PKG="/usr/bin/pkg"
 KEYDIR=/var/pkg/ssl
 
 # If we weren't passed at least two arguments, exit now.
 (( $# < 2 )) && exit $ZONE_SUBPROC_USAGE
 
-ZONENAME="$1"
-ZONEPATH="$2"
-# XXX shared/common script currently uses lower case zonename & zonepath
-zonename="$ZONENAME"
-zonepath="$ZONEPATH"
+zone=
+init_zone zone "$1" "$2"
+# Set ZONEPATH, etc.
+eval $(bind_legacy_zone_globals zone)
 
 shift; shift	# remove ZONENAME and ZONEPATH from arguments array
 
-ZONEROOT="$ZONEPATH/root"
 logdir="$ZONEROOT/var/log"
 
 #
@@ -190,8 +194,8 @@ gather_zone_publisher_details() {
 			typeset publisher.sticky=""
 			typeset publisher.preferred=""
 			typeset publisher.enabled=""
-			typeset -a publisher.origins=""
-			typeset -a publisher.mirrors=""
+			typeset -a publisher.origins
+			typeset -a publisher.mirrors
 			typeset publisher.name=$name
 			typeset publisher.keyfile=""
 			typeset publisher.certfile=""
@@ -297,11 +301,11 @@ print_publisher_pkg_defn() {
 		args="$args -P"
 	fi
 
-	for origin in ${publisher.origins[*]}; do
+	for origin in "${publisher.origins[@]}"; do
 		args="$args -g $origin"
 	done
 
-	for mirror in ${publisher.mirrors[*]}; do
+	for mirror in "${publisher.mirrors[@]}"; do
 		args="$args -m $mirror"
 	done
 
@@ -370,125 +374,17 @@ if [ $noexecute -eq 1 ]; then
 	exit $ZONE_SUBPROC_OK
 fi
 
-LOGFILE=$(/usr/bin/mktemp -t -p /var/tmp $ZONENAME.attach_log.XXXXXX)
+LOGFILE=$(/usr/bin/mktemp -t -p /var/tmp ${zone.name}.attach_log.XXXXXX)
 if [[ -z "$LOGFILE" ]]; then
 	fatal "$e_tmpfile"
 fi
 exec 2>>"$LOGFILE"
-
 log "$m_attach_log" "$LOGFILE"
 
-#
-# TODO - once sxce is gone, move the following block into
-# usr/lib/brand/shared/common.ksh code to share with other brands using
-# the same zfs dataset logic for attach. This currently uses get_current_gzbe
-# so we can't move it yet since beadm isn't in sxce.
-#
-
-# Validate that the zonepath is not in the root dataset.
-pdir=`dirname $ZONEPATH`
-get_zonepath_ds $pdir
-fail_zonepath_in_rootds $ZONEPATH_DS
-
-EXIT_CODE=$ZONE_SUBPROC_NOTCOMPLETE
-
-if [[ "$install_media" == "-" ]]; then
-	#
-	# Since we're using a pre-existing dataset, the dataset currently
-	# mounted on the {zonepath}/root becomes the active dataset.  We
-	# can't depend on the usual dataset attributes to detect this since
-	# the dataset could be a detached zone or one that the user set up by
-	# hand and lacking the proper attributes.  However, since the zone is
-	# not attached yet, the 'install_media == -' means the dataset must be
-	# mounted at this point.
-	#
-	ACTIVE_DS=`mount -p | nawk -v zroot=$ZONEROOT '{
-	    if ($3 == zroot && $4 == "zfs")
-		    print $1
-	}'`
-
-	[[ -z "$ACTIVE_DS" ]] && fatal "$f_no_active_ds_mounted" $ZONEROOT
-
-	# Set up proper attributes on the ROOT dataset.
-	get_zonepath_ds $ZONEPATH
-	zfs list -H -t filesystem -o name $ZONEPATH_DS/ROOT >/dev/null 2>&1
-	(( $? != 0 )) && fatal "$f_no_active_ds"
-
-	# need to ensure zoned is off to set mountpoint=legacy.
-	zfs set zoned=off $ZONEPATH_DS/ROOT
-	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT "zoned=off"
-
-	zfs set mountpoint=legacy $ZONEPATH_DS/ROOT
-	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT \
-	    "mountpoint=legacy"
-	zfs set zoned=on $ZONEPATH_DS/ROOT
-	(( $? != 0 )) && fatal "$f_ds_config" $ZONEPATH_DS/ROOT "zoned=on"
-
-	#
-	# We're typically using a pre-existing mounted dataset so setting the
-	# following propery changes will cause the {zonepath}/root dataset to
-	# be unmounted.  However, a p2v with an update-on-attach will have
-	# created the dataset with the correct properties, so setting these
-	# attributes won't unmount the dataset.  Thus, we check the mount
-	# and attempt the remount if necessary.
-	#
-	get_current_gzbe
-	zfs set $PROP_PARENT=$CURRENT_GZBE $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS \
-	    "$PROP_PARENT=$CURRENT_GZBE"
-	zfs set $PROP_ACTIVE=on $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "$PROP_ACTIVE=on"
-	zfs set canmount=noauto $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "canmount=noauto"
-	zfs set zoned=off $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "zoned=off"
-	zfs inherit mountpoint $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "'inherit mountpoint'"
-	zfs inherit zoned $ACTIVE_DS
-	(( $? != 0 )) && fatal "$f_ds_config" $ACTIVE_DS "'inherit zoned'"
-
-	mounted_ds=`mount -p | nawk -v zroot=$ZONEROOT '{
-	    if ($3 == zroot && $4 == "zfs")
-		    print $1
-	}'`
-
-	if [[ -z $mounted_ds ]]; then
-		mount -F zfs $ACTIVE_DS $ZONEROOT || fatal "$f_zfs_mount"
-	fi
-else
-	#
-	# Since we're not using a pre-existing ZFS dataset layout, create
-	# the zone datasets and mount them.  Start by creating the zonepath
-	# dataset, similar to what zoneadm would do for an initial install.
-	#
-	zds=$(zfs list -H -t filesystem -o name $pdir 2>/dev/null)
-	if (( $? == 0 )); then
-		pnm=$(/usr/bin/basename $ZONEPATH)
-		# The zonepath dataset might already exist.
-		zfs list -H -t filesystem -o name $zds/$pnm >/dev/null 2>&1
-		if (( $? != 0 )); then
-			zfs create "$zds/$pnm"
-			(( $? != 0 )) && fatal "$f_zfs_create"
-			vlog "$m_zfs"
-		fi
-	fi
-
-	create_active_ds
-fi
-
-#
-# The zone's datasets are now in place.
-#
-
-log "$m_attach_root" "$ZONEROOT"
-# note \n to add whitespace
-log "$m_attach_ds\n" "$ACTIVE_DS"
-
-install_image "$inst_type" "$install_media"
-
-#
-# End of TODO block to move to common code.
-#
+# Remember what was mounted on the zone root in case the attach fails.
+get_ds_from_path "${zone.root}" ACTIVE_DS
+attach_datasets -t "$inst_type" -m "$install_media" zone
+migrate_export zone
 
 #
 # Perform a sanity check to confirm that the image is not a global zone.
diff --git a/src/brand/image_install b/src/brand/image_install
--- a/src/brand/image_install
+++ b/src/brand/image_install
@@ -19,8 +19,9 @@
 #
 # CDDL HEADER END
 #
-# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
-# Use is subject to license terms.
+
+#
+# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
 #
 
 #
@@ -97,14 +98,8 @@ trap trap_exit EXIT
 # If we weren't passed at least two arguments, exit now.
 (( $# < 2 )) && exit $ZONE_SUBPROC_USAGE
 
-ZONENAME="$1"
-ZONEPATH="$2"
-# XXX shared/common script currently uses lower case zonename & zonepath
-zonename="$ZONENAME"
-zonepath="$ZONEPATH"
-
-ZONEROOT="$ZONEPATH/root"
-
+init_zone zone "$1" "$2"
+eval $(bind_legacy_zone_globals zone)
 shift; shift	# remove zonename and zonepath from arguments array
 
 unset inst_type
@@ -204,8 +199,7 @@ exec 2>>$LOGFILE
 
 if (( $p2v_result != 0 )); then
 	log "$p2v_fail"
-	log ""
-	log "$install_fail"
+	log "\n$install_fail"
 	log "$install_log" "$LOGFILE"
 	exit $ZONE_SUBPROC_FATAL
 fi
@@ -224,10 +218,9 @@ rm -f $LOGFILE
 
 # Mount active dataset on the root.
 is_brand_labeled
-(( $? == 0 )) && mount_active_ds
+(( $? == 0 )) && mount_active_be -c zone
 
-log ""
-log "$m_complete" ${SECONDS}
+log "\n$m_complete" ${SECONDS}
 printf "$install_log\n" "$ZONEROOT/var/log/$ZONENAME.install$$.log"
 printf "$m_postnote\n"
 printf "$m_postnote2\n"
diff --git a/src/brand/uninstall b/src/brand/uninstall
--- a/src/brand/uninstall
+++ b/src/brand/uninstall
@@ -19,15 +19,10 @@
 #
 # CDDL HEADER END
 #
-#
-# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
-# Use is subject to license terms.
-#
 
 #
-# get script name (bname) and path (dname)
+# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
 #
-bname=`basename $0`
 
 #
 # common shell script functions
@@ -38,16 +33,13 @@ bname=`basename $0`
 #
 # options processing
 #
-zonename=$1
-if [ -z "$zonename" ]; then
-	printf "$f_abort\n" >&2
-	exit $ZONE_SUBPROC_FATAL
-fi
-zonepath=$2
-if [ -z "$zonepath" ]; then
-	printf "$f_abort" >&2
-	exit $ZONE_SUBPROC_FATAL
-fi
+
+# If we weren't passed at least two arguments, exit now.
+(( $# < 2 )) && fail_fatal "$f_abort"
+
+typeset zone
+init_zone zone "$1" "$2"
+eval $(bind_legacy_zone_globals zone)
 shift 2
 
 options="FhHnv"
@@ -101,7 +93,6 @@ shift `expr $OPTIND - 1`
 #
 # main
 #
-zoneroot=$zonepath/root
 
 nop=""
 if [[ -n "$opt_n" ]]; then
@@ -113,49 +104,28 @@ if [[ -n "$opt_n" ]]; then
 	ZONE_SUBPROC_OK=$ZONE_SUBPROC_FATAL
 fi
 
-#
-# We want uninstall to work in the face of various problems, such as a
-# zone with no delegated root dataset or multiple active datasets, so we
-# don't use the common functions.  Instead, we do our own work here and
-# are tolerant of errors.
-#
-
 # get_current_gzbe
-CURRENT_GZBE=`/sbin/beadm list -H | /bin/nawk -F\; '{
-	# Field 3 is the BE status.  'N' is the active BE.
-	if ($3 ~ "N")
-		# Field 2 is the BE UUID
-		print $2
-	}'`
+get_current_gzbe || fail_fatal "$f_no_gzbe"
 
-if [ -z "$CURRENT_GZBE" ]; then
-	print "$f_no_gzbe"
-fi
+# find all the zone BEs associated with this global zone BE.
+typeset -a belist
+if [[ -n "$CURRENT_GZBE" ]]; then
+	zfs list -H -t filesystem -o $PROP_PARENT,name -r -d 1 \
+	    ${zone.ROOT_ds} 2>/dev/null | while IFS=$'\t' read uid fs; do
 
-uninstall_get_zonepath_ds
-uninstall_get_zonepath_root_ds
+		# Skip the ROOT dataset
+		[[ "$fs" == "${zone.ROOT_ds}" ]] && continue
 
-# find all the zone BEs datasets associated with this global zone BE.
-unset fs_all
-(( fs_all_c = 0 ))
-if [ -n "$CURRENT_GZBE" ]; then
-	/sbin/zfs list -H -t filesystem -o $PROP_PARENT,name \
-	    -r $ZONEPATH_RDS |
-	    while IFS="	" read uid fs; do
-
-		# only look at filesystems directly below $ZONEPATH_RDS
-		[[ "$fs" != ~()($ZONEPATH_RDS/+([^/])) ]] &&
-			continue
-
-		# match by PROP_PARENT uuid
-		[[ "$uid" != ${CURRENT_GZBE} ]] &&
-			continue
-
-		fs_all[$fs_all_c]=$fs
-		(( fs_all_c = $fs_all_c + 1 ))
+		#
+		# match by PROP_PARENT uuid.  If the uuid is not set ("-"), the
+		# BE is invalid (interrupted install?) and should be deleted.
+		#
+		if [[ $uid == "-" || $uid == "${CURRENT_GZBE}" ]] ; then
+			a_push belist "$(basename "$fs")"
+		fi
 	done
 fi
 
-destroy_zone_datasets
+destroy_zone_datasets zone -b belist
 
 exit $ZONE_SUBPROC_OK
